apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - tasks/git-clone.yaml
  - tasks/maven-build.yaml
  - tasks/unit-test.yaml
  - tasks/sonarqube-task.yaml
  - tasks/trivy-fs-task.yaml
  - tasks/trivy-secret-task.yaml
  - tasks/trivy-image-task.yaml
  - tasks/buildah.yaml
  - pipeline/java-maven-build.yaml