apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: maven-build
spec:
  params:
    - name: goals
      type: string
      default: "clean package"

  workspaces:
    - name: source

  steps:
    - name: build
      image: maven:3.9-eclipse-temurin-21
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -eu
        mvn $(params.goals)