apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: unit-test

spec:
  params:
    - name: project-dir
      type: string
      default: "applications/sample-java-app"

  workspaces:
    - name: source

  steps:
    - name: test
      image: maven:3.9-eclipse-temurin-21
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -eu

        echo "Workspace:"
        pwd

        echo "Application directory:"
        echo "$(params.project-dir)"

        cd "$(params.project-dir)"

        echo "Build directory:"
        pwd

        echo "Files:"
        ls -la

        mvn test