---
aws_region: "ap-south-1"

ebs_csi_chart_version: "2.66.0"

ebs_csi_release_name: "aws-ebs-csi-driver"

ebs_csi_helm_repo_name: "aws-ebs-csi-driver"

ebs_csi_helm_repo_url: "https://kubernetes-sigs.github.io/aws-ebs-csi-driver"

ebs_csi_namespace: "kube-system"

ebs_csi_storage_class_name: "ebs-gp3"

ebs_csi_volume_type: "gp3"

ebs_csi_fs_type: "ext4"

ebs_csi_volume_binding_mode: "WaitForFirstConsumer"

ebs_csi_reclaim_policy: "Delete"

ebs_csi_allow_volume_expansion: true

ebs_csi_controller_name: "ebs-csi-controller"

ebs_csi_node_name: "ebs-csi-node"