apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: buildah-test
  namespace: tekton-ci

spec:
  serviceAccountName: ci-serviceaccount

  taskRef:
    name: buildah

  params:
    - name: image
      value: docker.io/<YOUR_DOCKERHUB_USERNAME>/sample-java-app:buildah-test

    - name: dockerfile
      value: Dockerfile

    - name: context
      value: .

    - name: artifact
      value: target/sample-java-app-1.0.0.jar

  workspaces:
    - name: source
      emptyDir: {}