apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "pradeepranjan22",
          "password": "dckr_pat_T4SMafc6KINYgOFaUx0gNvEKdu4"
        }
      }
    }